language: c




sudo: required

os:
  - linux

env:
  - CC=gcc PROFILE=debug
  - CC=gcc PROFILE=release




before_install:
  - make PROFILE="$PROFILE" CC="$CC" make-debug

install:
  - make clean PROFILE="$PROFILE" CC="$CC" libcompy
  - sudo make install
  - make --directory=submodules/serum --no-print-directory PROFILE=release libserum
  - sudo make --directory=submodules/serum --no-print-directory install


before_script:
  - make clean PROFILE="$PROFILE" CC="$CC" compy

script:
  - make test
