CFLAGS_EXTRA = -DCOMPY_COLOR=1




bin/compy: $(call getfiles,compy/)
	@echo -n "=> $@";
	@mkdir -p $(@D);
	@$(CC) -o $@ $^ $(shell ((test -f bin/libcompy.so && realpath bin/libcompy.so) || echo '-lcompy'));
	@echo " (done)";


pre-compy:
	@echo $(SECTION_EOL)

compy: pre-compy bin/compy
