CFLAGS_EXTRA = -DCOMPY_COLOR=1




bin/compy: bin/libserum.so
bin/compy: $(call getfiles,compy/)
	@echo -n "=> $@";
	@mkdir -p $(@D);
	@$(CC) -o $@ $^ $(shell ((test -f bin/libcompy.so && realpath bin/libcompy.so) || echo '-lcompy')) $(shell ((test -f bin/libserum.so && realpath bin/libserum.so) || echo '-lserum'));
	@echo " (done)";


pre-compy:
	@echo $(SECTION_EOL)

compy: libcompy
compy: pre-compy bin/compy
